### ISSUE TITLE
checksum function

### ISSUE THREAD

**Issue by albertobsd** [jvirkki/libbloom#24]
I propose to have some checksum function that the user can call on request.

Lets to call this new funtion `bloom_checksum`

```
int bloom_checksum(struct bloom * bloom)
{
	return (murmurhash2(bloom->bf, bloom->bytes, 0x9747b28c) == bloom->checksum);
}
```

This depend also of some internal variable called checksum in the bloom filter structure, the hash function can be murmurhash2, xxhash64 or some other.

Actually im doing this with sha256 outside of the library.

The user can call to another function to indicate that the data in the bloom filter is not going to be modified anymore and construct the internal checksum and then call the  bloom checksum function every 2 days or some else trigger.

When someone run an application that only runs for some seconds there is no need to call that function, but what happen in the long run, what if there is some application that use the bloom filter to do something  "critical" for some months or a year, well in those case we need to run some checksum to ensure that the memory is not corrupted by some memory error, electrical failures, radiation or even cosmic particles. I know those scenarios are unlikely to happened, but the history show us that it actually happen some times ( https://www.youtube.com/watch?v=AaZ_RSt0KP8 ).

Usually ECC memory solve most of those cases but what happened if you don't have access to that kind of solutions.

Anyway this is only a suggestion for your excellent library. i'm using it for a long time with a lot of modifications to handle more than 128 GB of bf data

Best regards!

**Comment by jvirkki** [comment]
ECC RAM is really the best answer for this use case.

If you call the checksum every two days, all requests between those checks are subject to potential corrupted memory bits. While rare, it does happen. I remember some of the early Sun systems having problems with this due to lack of ECC RAM at the time. Even if you were to call the checksum function before every singe request, there's still no guarantee corruption can't happen between check and use (TOCTOU).

That means your code must always handle the false negative case due to bit corruption anyway (and the false positives since that's the nature of bloom filters). Since that handling code needs to be always present, and the bit errors due to RAM corruption will be exceedingly rare, does the checksum function add any value other than more overhead?

It'd be easy enough to add, but playing devils advocate to see if there is any value.

**Comment by jvirkki** [comment]
I don't think I'll add this for the reasons noted above.

As mentioned in the first comment, client code can do this easily enough by running a hash on bloom->bf (or even the entire bloom struct) periodically if needed.
